```reshape()``` - <br>
```sum()``` - <br>
```np.add.reduce()``` - <br>
```np.arrange(12).reshape((3,4))``` - <br>


In [68]:
import numpy as np
# import random as rand

a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[23,1,34,5], [45,0,7,1]])
print('Array: ',a[0], a[1])


rand = np.random.RandomState(51)
x = rand.randint(4, size=10)

print([x[4], x[7], x[2]])
ind = [2,7,4]
print(x[ind])

print('a.max: ', a.max())
print('a.min: ', a.min())
print('a.sum: ', a.sum())
print('a.max(axis = 0): ', a.max(axis=0))
print('a.min(axis = 0): ', a.min(axis=0))
print('a.max(axis = 1): ',a.max(axis=1))
print('a.min(axis = 1): ',a.min(axis=1))


print('+',a+b)
print('-',a-b)
try:
    print('/',a/b)
except Exception:
    print('Cannot be divided by 0')
print('*',a*b)

Array:  [1 2 3 4] [5 6 7 8]
[1, 1, 1]
[1 1 1]
a.max:  8
a.min:  1
a.sum:  36
a.max(axis = 0):  [5 6 7 8]
a.min(axis = 0):  [1 2 3 4]
a.max(axis = 1):  [4 8]
a.min(axis = 1):  [1 5]
+ [[24  3 37  9]
 [50  6 14  9]]
- [[-22   1 -31  -1]
 [-40   6   0   7]]
/ [[0.04347826 2.         0.08823529 0.8       ]
 [0.11111111        inf 1.         8.        ]]
* [[ 23   2 102  20]
 [225   0  49   8]]


C:\Users\Rajesh\AppData\Local\Temp\ipykernel_25976\2918566871.py:28: RuntimeWarning: divide by zero encountered in divide
  print('/',a/b)


## 30 Aug 2023




### **Slicing of matrices**

```arr[row, col]``` - first param will be row, second coll <br>
```py
    arr[:2, ]
```
---
> blockquote

| **Syntax** | **Description** |
| -------- | --------- |
| Header | Title |
```
{
    "firstname": "john",
    "lastname":"smith",
    "age": "34"
}
```

### Fancy indexing


In [37]:
import numpy as np

arr = np.array([[23,34,1,3], [4,76,5,-4], [1,2,0,67]])


print(arr[:2, 1:])


my_arr = np.array(['bob', 'rob', 'hob', 'nob', 'aob'])
print(my_arr == 'bob')
mask = (my_arr == 'bob') | (my_arr == 'aob')

print(np.array(10))

matrix = np.array([[0,1,2,3,4,5], 
                   [10,11,12,13,14,15],
                   [20,21,32,42,4,5],
                   [30,31,32,32,34,35],
                   [40,41,42,43,44,45],
                   [50,51,52,53,54,55]])
print(matrix)

print('\n\nMatrix:\n',matrix[:,[1,2,3,4,5]])




matrix1 = np.array(
    [
        np.arange(0,6),
        np.arange(10,16),
        np.arange(20,26),
        np.arange(30,36),
        np.arange(40,46)
    ]
)
print('\n\nMatrix1: \n',matrix1)
print('\nIndexing using tuples: ', matrix1[(0,1,2,3,4),(1,2,3,4,5)])

sorted_arr = matrix1[np.argsort(matrix1)]

[[34  1  3]
 [76  5 -4]]
[ True False False False False]
10
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 32 42  4  5]
 [30 31 32 32 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


Matrix:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 32 42  4  5]
 [31 32 32 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]


Matrix1: 
 [[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]]

Indexing using tuples:  [ 1 12 23 34 45]


IndexError: index 5 is out of bounds for axis 0 with size 5

## Sort in Numpy
```py
print(np.sort(x, axis=0))
```
Axis 0 is column and axis 1 is row
```py
print(np.sort(x,[::-1]))
```
Sorts in descending order 

```Indexing -boolean```

In [43]:
x = np.array([10,34,1,32,5])
print(np.sort(x, axis=0))

print(np.argsort(x))
print('Sorting using fancy indexing')
print(x[np.argsort(x)])
print(x[np.argsort(-x)])




[ 1  5 10 32 34]
[2 4 0 3 1]
Sorting using fancy indexing
[ 1  5 10 32 34]
[34 32 10  5  1]


### ```Structured array```


In [12]:
dtype = [('person_names', 'U9'), ('person_ages', 'i8'), ('python_programmer', 'bool')]
data = np.array([('Ram', 25, True), ('Sita', 23, False), ('Arnav', 45, True), ('Ethan', 18, False)], dtype=dtype)

print(data[np.where(data['person_ages'] < 30)])



[('Ram', 25,  True) ('Sita', 23, False) ('Ethan', 18, False)]



| **Character** | **Description** |	**Example** |
|---|---|---|
'b '	|Byte	|np.dtype('b')
'i'	|Signed integer|	np.dtype('i4') == np.int32
'u'	|Unsigned integer|	np.dtype('u1') == np.uint8
'f'	|Floating point|	np.dtype('f8') == np.int64
'c'	|Complex floating point|	np.dtype('c16') == np.complex128
'S','a'| 	  String|	np.dtype('S5')
'U'	|Unicode  string|	np.dtype('U') == np.str_
'V'	|Raw data (void)|	np.dtype('V') == np.void

In [6]:
import numpy as np

np.dtype({
    'names': ('name', 'age', 'weight'),
    'formats': ('U10', 'i4', 'f8')
    })




dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

1. How are list and numpy different? <br>
 - Numpy is faster than list. It is of fixed type. Takes less space, and is faster to read from memory. It  doesn't to type checking(str, int, float) everytime.
 - In memory: Lists are not store in contigous memory locations.

```dtype='int32'``` - can specify the datatype and size required for the array. Used with arrange <br>



```py 
a.size # size of each element in the 
a.nbytes # 
a.ndim # dimension of the array 
n.itemsize
a.shape # will return the shape of your 
```



In [32]:
import numpy as np


a = np.array([[1,2,3,4,23,63,95], [41,62,3,94,43,117,6]], dtype='int16')
print(a.dtype, a.size)

print(a[0, 1:])
print(a[0, 1:6:2]) # startindex, stopindex and stepindex

#creating 3d array;
d3_array = np.array([[[12,34,542,89],[21,74,24,13], [986,24,15,75]]])
print(np.zeros((3,3)))

int16 14
[ 2  3  4 23 63 95]
[ 2  4 63]


TypeError: Cannot interpret '3' as a data type

### Initializing different types of array

```np.zeroes((shape here))``` - zeroes 
```np.ones((shape here))```

In [16]:
print(np.zeros((2,2,2,2)))
print(np.full((2,2), 45, dtype='float16'))
#for decimal values



#for integer values
print(np.random.randint(11, size=(3,3)))


[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[45. 45.]
 [45. 45.]]
[[ 3 10  6]
 [ 6  0  0]
 [ 4  1  8]]


In [24]:
z = np.ones((5,5))
print(z)

zero = np.zeros((3,3))
zero[1,1] = 9
print(zero)
z[1:4,1:4] = zero
print(z)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### In numpy arrays are copied by reference and not value.
TO prevent that from happening use ```copy()``` function.

In [31]:
my_arr = np.array([1,34,15,93,56])
my_array1 = my_arr.copy()
print(id(my_array1), id(my_arr))


print(np.array(np.arange(10,30, 3)))
print(np.random.randint(10,30, size=(3,3)))


2168015766032 2168015766512
[10 13 16 19 22 25 28]
[[27 26 11]
 [17 14 10]
 [14 28 29]]
